language: objective-c
xcode_workspace: Braintree.xcworkspace
xcode_scheme:
  - Braintree-Specs
  - Braintree-API-Specs
  - Braintree-Payments-UI-Specs
  - Braintree-PayPal-Specs
install: bundle install && bundle exec pod install
