@import Foundation;
#import "BTErrors.h"

@class BTJSON;

@interface BTClientToken : NSObject <NSCoding, NSCopying>

/// The extracted authorization fingerprint
@property (nonatomic, readonly, copy) NSString *authorizationFingerprint;
/// The extracted configURL
@property (nonatomic, readonly, strong) NSURL *configURL;

#pragma mark -

//// Initialize a client token with a client token string generated by a Braintree Server SDK.
- (instancetype)initWithClientTokenString:(NSString *)JSONString error:(NSError **)error NS_DESIGNATED_INITIALIZER;

- (NSString *)originalValue;

@end
